[programs.localnet]
solana_twitter = "3szbwoWw7AMyT6n1NqojRkFsXjGghicFFz66GNi5nJxs"

[programs.devnet]
solana_twitter = "3szbwoWw7AMyT6n1NqojRkFsXjGghicFFz66GNi5nJxs"

[programs.mainnet]
solana_twitter = "3szbwoWw7AMyT6n1NqojRkFsXjGghicFFz66GNi5nJxs"


[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/mariemadeleine/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
my-custom-script = "echo 'hello pierric'"
copy-idl = "mkdir -p app/src/idl && cp target/idl/solana_twitter.json app/src/idl/solana_twitter.json"